TDMU/TDMU/Areas/Admin/Controllers/NewsController.cs
using TDMU.Common;
using Model.Dao;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TDMU.Areas.Admin.Controllers
{
    public class NewsController : BaseController
    {
        // GET: Admin/News
        public ActionResult Index()
        {
            var model = new NewsDao().ListAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            SetViewBag();
            return View();
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var service = new NewsDao().GetByID(id);
            SetViewBag(service.Cat_ID);
            return View(service);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(News news)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstant.USER_SESSION];
                news.Date = DateTime.Now;
                news.CreateBy = session.UserName;
                news.Url = CastString.Cast(news.Name);
                var dao = new NewsDao();
                long id = dao.Insert(news);
                if (id > 0)
                {
                    return RedirectToAction("Index", "News");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm tin tức không thành công!");
                }
            }
            SetViewBag();
            return View("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(News news)
        {
            if (ModelState.IsValid)
            {
                var session = (UserLogin)Session[CommonConstant.USER_SESSION];
                news.Date = DateTime.Now;
                news.CreateBy = session.UserName;
                news.Url = CastString.Cast(news.Name);
                var dao = new NewsDao();
                var result = dao.Update(news);
                if (result)
                {
                    return RedirectToAction("Index", "News");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật tin tức không thành công");
                }
            }
            return View("Index");

        }

        [HttpDelete]
        public ActionResult Delete(long id)
        {
            new NewsDao().Delete(id);
            return RedirectToAction("Index");
        }

        public void SetViewBag(long? selectedID = null)
        {
            var dao = new CategoryNewsDao();
            ViewBag.Cat_ID = new SelectList(dao.GetList(), "ID", "Name", selectedID);
        }
    }
}

TDMU/TDMU/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TDMU.Controllers
{
    public class ItemsController : Controller
    {
        // GET: Items

        public ActionResult Index()
        {
            return View();
        }
    }
}

TDMU/TDMU/Controllers/NewsController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TDMU.Common;

namespace TDMU.Controllers
{
    public class NewsController : Controller
    {
        // GET: News   
        [CompressContent]
        public ActionResult Index()
        {
            var dao = new NewsDao();
            var model = dao.GetSlideNews();
            ViewBag.ListNews = dao.ListAllNews();
            return View(model);
        }

        [OutputCache(Duration = int.MaxValue, Location = System.Web.UI.OutputCacheLocation.Client, VaryByParam = "url")]
        [CompressContent]
        public ActionResult Detail(string url)
        {
            var model = new NewsDao().GetByUrl(url);
            return View(model);
        }
    }
}

TDMU/TDMU/Controllers/PhotoController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TDMU.Common;

namespace TDMU.Controllers
{
    public class PhotoController : Controller
    {
        //
        // GET: /Photo/
        [CompressContent]
        public ActionResult Index()
        {
            var dao = new PhotoDao().ListAllPhoto();
            return View(dao);
        }

       
        public ActionResult SlidePhoto()
        {
            var dao = new PhotoDao();
            var model = dao.ListAll();
            return PartialView(model);
        }
	}
}

TDMU/TDMU/Views/News/Detail.cshtml
@model Model.EF.News
@{
    ViewBag.Title = Model.Title + " - THU DAU MOT UNIVERSITY";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Menu{
    <li><a href="/home" title="Home">home</a></li>
	<li><a href="/about" title="About">About us</a></li>
    <li><a href="/news" class="active" title="News">news</a></li>
    <li><a href="/trainingologies" title="TRAINING OLOGIES">TRAINING OLOGIES</a></li>
    <li><a href="/cdio" title="CDIO">CDIO</a></li>
    <li><a href="/contact" title="Contact">contact</a></li>
}
@section Slide{
    <div class="page-desc-wrapper">
        <div class="container">
            <div class="page-desc">
                <h3>News</h3>
                <ol class="breadcrumb">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/news">News</a></li>
                    <li class="active">@Model.Name</li>
                </ol>
            </div>
        </div>
    </div>
}

@*@section UpEventsandPhoto{
    @{ Html.RenderAction("UpEvents", "Home");}
    @{ Html.RenderAction("SlidePhoto", "Photo");}
}*@
<div class="content">
    <div class="content-info">
        <h3>@Model.Name</h3>
        <span>By @Model.CreateBy Posted @Model.Date</span>
        <span class="quota" style="text-align: justify;">
            @Html.Raw(@Model.Description)
        </span>
        @*<img src="http://loremflickr.com/1280/720/city,building,maplestory,flower,natural,rain?random=1" />*@
    </div>
<style> .main-content img{ height: auto !important; width: 100% !important; } </style>
    <div class="main-content" style="text-align: justify;">
        @Html.Raw(Model.Detail)
    </div>
</div>

TDMU/TDMU/Views/News/Index.cshtml
@model List<Model.EF.News>
    @{
        ViewBag.Title = "News" + " - THU DAU MOT UNIVERSITY";
        Layout = "~/Views/Shared/_Layout.cshtml";
        List<Model.EF.News> list = ViewBag.ListNews;
    }
    @section Menu{
        <li><a href="/home" title="Home">home</a></li>
        <li><a href="/about" title="About">About us</a></li>
        <li><a href="/news" class="active" title="News">news</a></li>
        <li><a href="/trainingologies" title="TRAINING OLOGIES">TRAINING OLOGIES</a></li>
        <li><a href="/cdio" title="CDIO">CDIO</a></li>
        <li><a href="/contact" title="Contact">contact</a></li>
    }

    @*@section UpEventsandPhoto{
            @{ Html.RenderAction("UpEvents", "Home");}
            @{ Html.RenderAction("SlidePhoto", "Photo");}
        }*@

    <section>
        <div class="section-title">
            <h4><a href="/news">latest news</a></h4>
        </div>

        <!--news slider-->
        <div class="n-slider flexslider">
            <ul class="slides">
                @foreach (var item in Model)
                {
                    var url = "/news/" + item.Url + ".html";
                    <li>
                        <div class="news-slider-item">

                            <div class="n-img" style="background-image: url(@item.Image)"></div>
                            <a href="@url">
                                <div class="caption" style="color:white; font-size: 20px; width: 100%; height: auto; background: rgba(1, 1, 1, 0.45); padding:7px;">
                                    @item.Name
                                </div>
                            </a>
                        </div>
                    </li>
                }
            </ul>
        </div>
        <!--news slider./-->
    </section>
    <!--news./-->

    <div class="sep-30"></div>

    <!--blog./-->
    <section id="news">
        <div class="jplist-ios-button">
            <i class="fa fa-sort"></i>
            Trang
        </div>
        <div class="row list">
            @foreach (var item in list)
            {
                var url = "/news/" + item.Url + ".html";
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 list-item">
                    <div class="post post-md post-hoz ">
                        <div class="post-img">
                            <img alt="@item.Name" src="@item.Image" />
                        </div>
                        <div class="post-info">
                            <h4><a href="@url" title="@item.Name" @*class="post-title"*@>@item.Name</a></h4>
                            <p class="post-tag">
                                <span><i class="fa fa-clock-o"></i> @item.Date <i class="fa fa-user"></i> @item.CreateBy <i class="fa fa-tags"></i> @item.Keyword</span>
                            </p>
                            <p class="post-desc" style="text-align: justify;">@Html.Raw(@item.Description)</p>

                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jplist-panel box panel-top">

                    <div class="jplist-drop-down"
                         data-control-type="items-per-page-drop-down"
                         data-control-name="paging"
                         data-control-action="paging">

                        <ul>
                            @{ Html.RenderAction("Index", "Items");}
                        </ul>
                    </div>

                    <div class="jplist-label"
                         data-type="Page {current} of {pages}"
                         data-control-type="pagination-info"
                         data-control-name="paging"
                         data-control-action="paging">
                    </div>

                    <div class="jplist-pagination"
                         data-control-type="pagination"
                         data-control-name="paging"
                         data-control-action="paging">
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!--blog./-->
@section jsFooter{
        
        <script type="text/javascript">
            $(document).ready(function () {
               
                $('#news').jplist({
                    itemsBox: '.list'
                        , itemPath: '.list-item'
                        , panelPath: '.jplist-panel'
                });
            });
        </script>
}